### PR TITLE
Better method name parsing and mapping

### LINKED ISSUE #75: Object name appears in method name field
We're actually asserting on this behavior in tests...

https://github.com/microsoft/sourcemap-toolkit/blob/15f184ac12143bef79e134f3afae7a333d85e899/tests/SourcemapToolkit.CallstackDeminifier.UnitTests/StackTraceDeminifierEndToEndTests.cs#L34

This method is actually `window.onload`. I would accept either `onload` or `window.onload` for the method name, but `window` is not a method.

### PR DESCRIPTION
**Pull request by ian-craig**
Fixes #75 and makes the `MethodName` field usable for TypeScript callstacks. Previously I was only seeing the class name in this field.

If a fully qualified method name contains 2 or more parts, it's now split into 2 bindings. One exception is `foo.prototype` which is just treated as `foo`.

There is also a little additional work to combine these back into a method name, so the field in the resulting frames contains the fully qualified name.

e.g.

- `window.onload` => `[window, onload]` => `window.onload`
- `a.prototype.b` => `[a.prototype, b]` => `MyClass.myMethod`
- `a.prototype` => `[a]` => `MyClass`

### CODE REVIEW

File: src/SourceMapToolkit.CallstackDeminifier/FunctionFinderVisitor.cs [hunk 1]
```diff
@@ -110,15 +110,41 @@ private List<BindingInformation> GetBindings(FunctionObject node)
 			return null;
 		}
 
-		private BindingInformation ExtractBindingsFromBinaryOperator(BinaryOperator parentBinaryOperator)
+		private IEnumerable<BindingInformation> ExtractBindingsFromBinaryOperator(BinaryOperator parentBinaryOperator)
+		{
+			Member member = parentBinaryOperator.Operand1 as Member;
```
Comment (christiango) [inline src/SourceMapToolkit.CallstackDeminifier/FunctionFinderVisitor.cs]: Can you add some comments here describing what is going on here?
